#!/usr/bin/env perl
# vi: ts=4 sw=4
#
# OzTivo Programme Guide Grabber for Shepherd
# Chris Williams <shepherd@psychogeeks.com>
# Copyright Chris Williams, 2008.
#
# http://www.oztivo.net		OzTiVo TWiki
# http://tvguide.oztivo.net	TV Guide site, needs twiki login/password
# http://xml.oztivo.net/xmltv	XML files cache machine, copy from main machine
# http://www.oztivo.net/xmltv	XML files main machine (will be removed end of June 2008)

use strict;
use warnings;

use Getopt::Long;
use Shepherd::Common;
use XML::LibXML;
use URI::Escape;
use POSIX;
use Time::Local;

# ensure 'cache' directory exists (or is created) before the 'use HTTP::Cache'
# below or it'll fail
BEGIN {
	-d "cache" or mkdir "cache" or die "Cannot create directory cache: $!";
}

# Setup caching so we are good Netizens
# This works transparently under the LWP::* modules
#
use HTTP::Cache::Transparent (
	BasePath  => "cache",
	MaxAge	  => 8*24, # hours
	Verbose   => 0,
	NoUpdate  => 15*60,
	ApproveContent => sub { return $_[0]->is_success },
);


################################################################################
# Global variables
#
my $progname = 'oztivo';
my $nicename = 'OzTivo';
my $version = '2.61';
my $config_file = "$progname.pw";
my $output_file = undef;
my $channels_file;
my $ver;
my $ready_check;
my $configure;
my $region = undef;
my $days = 7;

# Channel to XMLTvID map from channels file
#
my $channels, my $opt_channels;

# User name and password from configuration file
#
my $user;
my $pw;


################################################################################
# Setup a mapping file to go from a Shepherd channel name to an OzTivo name
# Taking into consideration the region.
#
# The order of search for a mapping is;
# 	Region specific mapping (under numeric region code keys)
#	National mapping (under hash key 'National')
#	Pay TV mapping (under hash key 'PAY')
# First mapping found wins.
#
my %s_to_o_map = (
	'National' => {	# National channel mappings, all timeshifted
		'ABC2 / KIDS' => 'ABC2',
		'ABC3' => 'ABC3',
		'ABC News 24' => 'ABC-News24',
		#'7HD'=>'SevenHD-Mel',
		'Prime HD' => 'SevenHD', # no such thing yet
		'Nine HD' => 'NineHD',
		#'TEN HD' => 'TenHD',
		#'TEN HD'=>'TenHD-Vic',
		'9Go!' => 'GO',
		'7flix' => '7flix',
		'7mate' => '7mate',
		'ELEVEN' => 'ELEVEN',
	},
	'VIC' => {
		'ONE' => 'One-Vic',
		'One Digital' => 'One-Vic',
		'SBS 2' => 'SBSTWO-Vic',
		'7TWO' => '7TWO-Vic',
		'GEM' => 'GEM-Vic',
	},
	'NSW' => {
		'ONE' => 'One-NSW',
		'One Digital' => 'One-NSW',
		'SBS 2' => 'SBSTWO-NSW',
		'7TWO' => '7TWO-NSW',
		'GEM' => 'GEM-NSW',
	},
	'QLD' => {
		'ONE' => 'One-Qld',
		'One Digital' => 'One-Qld',
		'SBS 2' => 'SBSTWO-Qld',
		'7TWO' => '7TWO-Qld',
		'GEM' => 'GEM-Qld',
	},
	'WA' => {
		'ONE' => 'One-WA',
		'One Digital' => 'One-WA',
		'SBS 2' => 'SBSTWO-WA',
		'7TWO' => '7TWO-WA',
		'GEM' => 'GEM-WA',
	},
	'SA' => {
		'ONE' => 'One-SA',
		'One Digital' => 'One-SA',
		'SBS 2' => 'SBSTWO-SA',
		'7TWO' => '7TWO-SA',
		'GEM' => 'GEM-SA',
	},
	'NT' => {
		'ONE' => 'One-Dar',
		'One Digital' => 'One-Dar',
		'SBS 2' => 'SBSTWO-NT',
		'7TWO' => '7TWO-NT',
	},
	'ACT' => {
		'ONE' => 'One-NSW',
		'One Digital' => 'One-NSW',
		'SBS 2' => 'SBSTWO-NSW',
		'7TWO' => '7TWO-ACT',
		'GEM' => 'GEM-ACT',
	},
	'TAS' => {
		'ONE' => 'One-Tas',
		'One Digital' => 'One-Tas',
		'SBS 2' => 'SBSTWO-Tas',
		'7TWO' => '7TWO-Tas',
		'GEM' => 'GEM-Tas',
	},
	'67' => {	# NSW: Griffith
		'ABC' => 'ABC-NSW',
		'Prime' => 'PrimeS',
		'SBS' => 'SBS-NSW',
		'SC10' => 'SC10-NSW',
		'WIN' => 'WIN-NSW',
	},
	'90' => {	# VIC: Ballarat
		'ABC' => 'ABC-Vic',
		'Prime' => 'Prime-Vic',
		'SBS' => 'SBS-Vic',
		'SC10' => 'SC10-Vic',
		'WIN' => 'WIN-Vic',
		'Imparja' => 'IMP',
	},
	'63' => {	# NSW: Broken Hill
		'ABC' => 'ABC-NSW',
		'Central GTS/BKN' => 'GTS-BKN',
		'SBS' => 'SBS-NSW',
		'SC10' => 'SC10-NSW',
	},
	'102' => {	# WA: Regional
		'ABC' => 'ABC-WA',
		'Access 31' => '31-Per',
		'Golden West' => 'GWN-WA',
		'Nine' => 'Nine-WA',
		'SBS' => 'SBS-WA',
		'Seven' => 'Seven-WA',
		'TEN' => 'Ten-WA',
		'WIN' => 'WIN-WA',
	},
	'78' => {	# QLD: Gold Coast
		'ABC' => 'ABC-Qld',
		'NBN' => 'NWN-GC',
		'Nine' => 'Nine-Qld',
		'Prime' => 'Prime-GC',
		'SBS' => 'SBS-Qld',
		'Seven' => 'Seven-Bris',
		'SC10' => 'SC10-GC',
		'TEN' => 'Ten-Qld',
	},
	'255' => {	# QLD: Sunshine Coast
		'ABC' => 'ABC-Qld',
		'SBS' => 'SBS-Qld',
		'Seven' => 'Seven-Qld',
		'TEN' => 'Ten-Qld',
		'SC10' => 'SC10-Qld',
		'WIN' => 'Win-Qld',
	},
	'256' => {	# QLD: Toowoomba
		'ABC' => 'ABC-Qld',
		'SBS' => 'SBS-Qld',
		'Seven' => 'Seven-Qld',
		'SC10' => 'SC10-Qld',
		'WIN' => 'Win-Qld',
	},
	'258' => {	# QLD: Wide Bay
		'ABC' => 'ABC-Qld',
		'SBS' => 'SBS-Qld',
		'Seven' => 'Seven-Qld',
		'SC10' => 'Ten-Qld',
		'WIN' => 'Win-Qld',
	},
	'254' => {	# QLD: Rockhampton
		'ABC' => 'ABC-Qld',
		'SBS' => 'SBS-Qld',
		'Seven' => 'Seven-Qld',
		'SC10' => 'Ten-Qld',
		'WIN' => 'Win-Qld',
	},
	'253' => {	# QLD: Mackay
		'ABC' => 'ABC-Qld',
		'SBS' => 'SBS-Qld',
		'Seven' => 'Seven-Qld',
		'SC10' => 'Ten-Qld',
		'WIN' => 'Win-Qld',
	},
	'257' => {	# QLD: Townsville
		'ABC' => 'ABC-Qld',
		'SBS' => 'SBS-Qld',
		'Seven' => 'Seven-Qld',
		'SC10' => 'Ten-Qld',
		'WIN' => 'Win-Qld',
	},
	'79' => {	# QLD: Cairns
		'ABC' => 'ABC-Qld',
		'SBS' => 'SBS-Qld',
		'Seven' => 'Seven-Qld',
		'SC10' => 'Ten-Qld',
		'WIN' => 'Win-Qld',
	},
	'107' => {	# SA: Remote & Central
		'ABC' => 'ABC-SA',
		'Imparja' => 'IMP',
		'SBS' => 'SBS-SA',
		'SCTV Central' => 'Seven-SA',
	},
	'88' => {	# Tasmania
		'ABC' => 'ABC-Tas',
		'SBS' => 'SBS-Tas',
		'Southern Cross' => 'SC-Tas',
		'TDT' => 'TDT-Tas',
		'WIN' => 'Win-Tas',
	},
	'93' => {	# VIC: Geelong
		'ABC' => 'ABC-Vic',
		'Channel 31' => '31-Mel',
		'Nine' => 'Nine-Mel',
		'SBS' => 'SBS-Vic',
		'Seven' => 'Seven-Mel',
		'TEN' => 'Ten-Vic',
	},
	'106' => {	# NSW: Remote and Central
		'ABC' => 'ABC-NSW',
		'Imparja' => 'IMP',
		'Prime' => 'PrimeS',
		'SBS' => 'SBS-NSW',
		'SCTV Central' => 'Seven-Syd',
	},
	'126' => {	# ACT
		'ABC' => 'ABC-Can',
		'Prime' => 'Prime-Can',
		'SBS' => 'SBS-Can',
		'SC10' => 'Ten-Can',
		'WIN' => 'WIN-Can',
	},
	'82' => {	# SA: Renmark
		'ABC' => 'ABC-SA',
		'SBS' => 'SBS-SA',
		'WIN TEN' => 'TEN-SA',
		'WIN' => 'Win-Vic',
	},
	'74' => {	# NT: Darwin
		'ABC' => 'ABC-NT',
		'SBS' => 'SBS-NT',
		'Southern Cross' => 'Seven-Dar',
		'Nine' => 'Nine-NT',
		'DDT' => 'Ten-Dar',
	},
	'85' => {	# SA: South East SA
		'ABC' => 'ABC-SA',
		'SBS' => 'SBS-SA',
		'WIN TEN' => 'Ten-SA',
		'Seven' => 'WIN7-SA',
		'WIN Nine' => 'Nine-SA'
	},
	'83' => {	# SA: Riverland
		'ABC' => 'ABC-SA',
		'SBS' => 'SBS-SA',
		'WIN TEN' => 'TEN-SA',
		'WIN' => 'Win-Vic',
	},
	'95' => {	# VIC: Mildura/Sunraysia
		'ABC' => 'ABC-Vic',
		'Prime' => 'Prime-Vic',
		'SBS' => 'SBS-Vic',
		'TEN' => 'Ten-Vic',
		'SC10' => 'SC10-Vic',
		'WIN' => 'WIN-Vic',
	},
	'75' => {	# QLD: Brisbane
		'ABC' => 'ABC-Qld',
		'QCTV' => 'BRIZ',
		'Nine' => 'Nine-Qld',
		'SBS' => 'SBS-Qld',
		'Seven' => 'Seven-Bris',
		'TEN' => 'Ten-Qld',
	},
	'94' => {	# VIC: Melbourne
		'ABC' => 'ABC-Vic',
		'Channel 31' => '31-Mel',
		'Nine' => 'Nine-Mel',
		'SBS' => 'SBS-Vic',
		'Seven' => 'Seven-Mel',
		'TEN' => 'Ten-Vic',
	},
	'108' => {	# NT: Remote & Central
		'ABC' => 'ABC-NT',
		'Imparja' => 'IMP',
		'SBS' => 'SBS-NT',
		'SCTV Central' => 'Seven-Dar',
	},
	'114' => {	# QLD: Remote & Central
		'ABC' => 'ABC-Qld',
		'Imparja' => 'IMP',
		'SBS' => 'SBS-Qld',
		'SCTV Central' => 'Seven-Qld',
	},
	'184' => {	# NSW: Newcastle
		'ABC' => 'ABC-NSW',
		'NBN' => 'NBN',
		'Prime' => 'PrimeN',
		'SBS' => 'SBS-NSW',
		'SC10' => 'SC10-NSW',
		'ONE' => 'One-Newc',
	},
	'69' => {	# NSW: Tamworth
		'ABC' => 'ABC-NSW',
		'NBN' => 'NBN',
		'Prime' => 'PrimeN',
		'SBS' => 'SBS-NSW',
		'SC10' => 'SC10-NSW',
	},
	'71' => {	# NSW: Wollongong
		'ABC' => 'ABC-NSW',
		'Prime' => 'PrimeS',
		'SBS' => 'SBS-NSW',
		'SC10' => 'SC10-NSW',
		'WIN' => 'WIN-NSW',
	},
	'259' => {	# NSW: Far South Coast
		'ABC' => 'ABC-NSW',
		'Prime' => 'Prime-Can',
		'SBS' => 'SBS-NSW',
		'SC10' => 'SC10-NSW',
		'WIN' => 'WIN-NSW',
	},
	'261' => {	# NSW: Lismore/Coffs Harbour
		'ABC' => 'ABC-NSW',
		'NBN' => 'NBN',
		'Prime' => 'PrimeN',
		'SBS' => 'SBS-NSW',
		'SC10' => 'SC10-NSW',
	},
	'262' => {	# NSW: Orange/Dubbo
		'ABC' => 'ABC-NSW',
		'Prime' => 'PrimeS',
		'SBS' => 'SBS-NSW',
		'SC10' => 'SC10-NSW',
		'WIN' => 'WIN-NSW',
	},
	'263' => {	# NSW: Taree/Port Macquarie
		'ABC' => 'ABC-NSW',
		'NBN' => 'NBN',
		'Prime' => 'PrimeN',
		'SBS' => 'SBS-NSW',
		'SC10' => 'SC10-NSW',
	},
	'264' => {	# NSW: Wagga Wagga
		'ABC' => 'ABC-NSW',
		'Prime' => 'PrimeS',
		'SBS' => 'SBS-NSW',
		'SC10' => 'SC10-NSW',
		'WIN' => 'WIN-NSW',
	},
	'81' => {	# SA: Adelaide
		'ABC' => 'ABC-SA',
		'C31 Adelaide' => '31-Adl',
		'Nine' => 'Nine-SA',
		'SBS' => 'SBS-SA',
		'SBS HD' => 'SBS-SA',
		'Seven' => 'Seven-SA',
		'TEN' => 'Ten-SA',
	},
	'98' => {	# VIC: Gippsland
		'ABC' => 'ABC-Vic',
		'Imparja' => 'IMP',
		'Prime' => 'Prime-Vic',
		'SBS' => 'SBS-Vic',
		'SCTV Central' => 'Seven-Mel',
		'SC10' => 'Ten-Vic',
		'WIN' => 'WIN-Vic',
	},
	'66' => {	# NSW: Central Coast
		'ABC' => 'ABC-NSW',
		'NBN' => 'NBN',
		'Nine' => 'Nine-Syd',
		'Prime' => 'PrimeN',
		'SBS' => 'SBS-NSW',
		'Seven' => 'Seven-Syd',
		'Sthn Cross TEN' => 'SC10-NSW',
		'TEN' => 'SC10-NSW',
	},
	'73' => {	# NSW: Sydney
		'ABC' => 'ABC-NSW',
		'Channel NSW' => undef,
		'Nine' => 'Nine-Syd',
		'SBS' => 'SBS-NSW',
		'Seven' => 'Seven-Syd',
		'TEN' => 'SC10-NSW',
		'TVS' => '31-Syd',
	},
	'101' => {	# WA: Perth
		'ABC' => 'ABC-WA',
		'Access 31' => '31-Per',
		'Nine' => 'Nine-WA',
		'SBS' => 'SBS-WA',
		'Seven' => 'Seven-WA',
		'TEN' => 'Ten-WA',
	},
	'86' => {	# SA: Spencer Gulf
		'ABC' => 'ABC-SA',
		'Central GTS/BKN' => 'GTS-BKN',
		'Nine' => 'Nine-SA',
		'SBS' => 'SBS-SA',
		'Sthn Cross TEN' => 'SC10-NSW',
	},
	'266' => {	# VIC: Bendigo
		'ABC' => 'ABC-Vic',
		'Prime' => 'Prime-Vic',
		'SBS' => 'SBS-Vic',
		'SC10' => 'SC10-Vic',
		'WIN' => 'WIN-Vic',
		'Imparja' => 'IMP',
	},
	'267' => {	# VIC: Shepparton
		'ABC' => 'ABC-Vic',
		'Prime' => 'Prime-Vic',
		'SBS' => 'SBS-Vic',
		'SC10' => 'SC10-Vic',
		'WIN' => 'WIN-Vic',
	},
	'268' => {	# VIC: Albury/Wodonga
		'ABC' => 'ABC-Vic',
		'Prime' => 'Prime-Vic',
		'SBS' => 'SBS-Vic',
		'SC10' => 'SC10-Vic',
		'WIN' => 'WIN-Vic',
	},
	'PAY' => {	# Pay channels
		 '1112' => 'HITS+2',
		 '111' => 'HITS',
		 '13THSTREET' => '13THST',
		 '13thSTREET2' => '13THST+2',
		 #'13THSTREET2' => '',
		 #'3DChannel' => '',
		 'ACC' => 'ACC',
		 #'' => 'ADULT',
		 #'' => 'ADULT1',
		 #'' => 'ADULT2',
		 'Action' => 'FMACT',
		 'Action2' => 'FMACT+2',
		 #'ActionHD' => '',
		 'AE' => 'AandE',
		 #'AEHD' => '',
		 'AIR' => 'AIRACT',
		 'AlJazeeraEnglish' => 'ALJA',
		 'AnimalPlanet' => 'ANIMAL',
		 'Antenna' => 'ANT',
		 'APAC' => 'A-PAC',
		 #'' => 'ARCADE',
		 'ARENA' => 'ARNA',
		 'ARENA2' => 'ARNA+2',
		 #'ArenaHD' => '',
		 'Arts' => 'STUDIO',
		 #'ArtsHD' => '',
		 #'' => 'ART',
		 'AURORA' => 'AUR',
		 #'' => 'AV',
		 'BBCFirst' => 'BBCF',
		 #'BBCFirstHD' => ''
		 'BBCKnowledge' => 'BBCK',
		 #'BBCKnowledgeHD' => '',
		 'BBCWorldNews' => 'BBC',
		 #'beINSports' => '' 
		 #'' => 'BETHTV',
		 'Bio' => 'BIOG',
		 'Bloomberg' => 'BLM',
		 #'' => 'BNTV',
		 'Boomerang' => 'BOOM',
		 'Boxsets' => 'BOXS',
		 #'BoxsetsHD' => '',
		 #'' => 'CANALSUR',
		 'CartoonNetwork' => 'CART',
		 'Cbeebies' => 'CBEEB',
		 #'' => 'CCTV4',
		 #'CCD' => '',
		 #'CCTV-9Documentary' => '',
		 'CCTVNews' => 'CCTVN',
		 'ChannelV' => 'V',
		 #'' => 'Cinemax',
		 #'' => 'CLUBV',
		 'CMC' => 'CMC',
		 #'' => 'CMTE',
		 #'' => 'CMTER1',
		 #'' => 'CMTER2',
		 #'' => 'CMTER3',
		 #'' => 'CMTER4',
		 'CNBC' => 'CNBC',
		 'CNN' => 'CNNI',
		 #'' => 'CNNfn',
		 'Comedy' => 'FMCOM',
		 #'ComedyHD' => '',
		 'ComedyChannel' => 'CMDY',
		 'Comedy2' => 'CMDY+2',
		 'Crime' => 'CRIME',
		 #'' => 'CVISION',
		 #'' => 'D4NEWS',
		 #'Daystar' => '',
		 #'' => 'DAAI',
		 #'' => 'DIG',
		 #'' => 'Digital4',
		 #'' => 'DIG-jazz',
		 'DiscoveryChannel2' => 'DISC+2',
		 'DiscoveryChannel' => 'DISC',
		 'DiscoveryHealth' => 'HEALTH',
		 'DiscoveryKids' => 'DKIDS',
		 #'DiscoveryRealTime' => 'DISCRT',
		 'DiscoveryScience' => 'SCIENCE',
		 'DiscoveryTurbo' => 'DTM',
		 #'DiscoveryWorldHD' => '',
		 'DiscoveryTurbo2' => 'DTM+2',
		 'DisneyChannel' => 'DISN',
		 'DisneyJunior' => 'DJNR',
		 #'DisneyMovies2' => '',
 		 'DisneyXD' => 'DISXD',
		 #'' => 'DWTV',
		 'E!' => 'E!',
		 #'' => 'ENEWS-GE',
		 #'' => 'ENEWSI',
		 #'' => 'ENEWS-IT',
		 #'' => 'ENEWSS',
		 #'' => 'ENEWS-SP',
		 #'' => 'ERITV',
		 #'' => 'ERTW',
		 'ESPN' => 'ESPN',
		 'ESPN2' => 'ESPN2',
		 #'ESPNHD' => '',
		 #'ESPN2HD' => '',
		 #'' => 'EURONEWS',
		 'Eurosport' => 'EUROSPORT',
		 #'EurosportHD' => '',
		 'EurosportNews' => 'ESNEWS',
		 #'' => 'EWTN',
		 'EXPO' => 'EXPO',
		 'Family' => 'FMFAM',
		 'Family2' => 'FMFAM+2',
		 #'FamilyHD' => '',
		 #'FashionTV' => 'FASH',
		 #'FMC' => 'FMC',
		 'FOX82' => 'FOX8+2',
		 'FOX8' => 'FOX8',
		 #'FOX8HD' => '',
		 'FOXClassics2' => 'CLAS+2',
		 'FOXClassics' => 'CLAS',
		 'FOX FOOTY' => 'FFC',
		 #'FOX FOOTY HD' => '',
		 'FOXNEWS' => 'FOXN',
		 'FOXSPORTS1' => 'FS1',
		 #'FoxSports1HD' => '',
		 'FOXSPORTS2' => 'FS2',
		 #'FoxSports2HD' => '',
		 'FOXSPORTS3' => 'FS3',
		 #'FoxSports3HD' => '',
		 'FOXSPORTS4' => 'FS4',
		 #'FOXSPORTS4HD' => '',
		 'FOXSPORTS5' => 'FS5',
		 #'FOXSPORTS4HD' => '',
		 'FOXSPORTSNews' => 'FSN',
		 #'FOXSPORTSNewsHD' => '',
		 'FoxtelMoviesDisneySD' => 'DISMOV',
		 #'FoxtelMoviesDisneyHD' => '',
		 #'FOXSPORTSPLUS' => '',
		 'FUELTV' => 'FUEL',
		 'FX' => 'FX',
		 'FX2' => 'FX+2',
		 #'FXHD' => '',
		 #'' => 'GUIDE',
		 #'' => 'GWORLD',
		 #'' => 'HIST+2',
		 #'' => 'HOUSE',
		 #'HOWTOChannel' => 'HOWTO',
		 #'' => 'IMP',
		 #'' => 'ISHTAR',
		 #'' => 'JJJ',
		 'KidsCo' => 'KIDSCO',
		 #'' => 'LBC',
		 #'' => 'LEONARDO',
		 'LifeStyleChannel' => 'LIFE',
		 'LifeStyleChannel2' => 'LIFE+2',
		 #'LifeStyleHD' => '',
		 'LifeStyleHOME' => 'LHOME',
		 'LifeStyleFOOD2' => 'FOOD+2',
		 'LifeStyleFOOD' => 'FOOD',
		 'LifeStyleYOU' => 'LYOU',
		 'LifStyleYOU2' => 'LYOU+2',
		 #'' => 'LNTV',
		 #'' => 'MACQD',
		 #'' => 'MAIN',
		 #'MainEvent' => '',
		 'Masterpiece' => 'FMMAST',
		 #'MasterpieceHD' => '',
		 'MAX' => 'max',
		 #'' => 'MCMTop',
		 #'' => 'MCMTOP',
		 #'' => 'MINDGAMES',
		 #'MOVIEEXTRA' => 'MOVX',
		 #'MOVIEGREATS' => 'MOVG',
		 #'MOVIEONE' => 'MOV1',
		 #'MOVIEONEHD' => '',
		 #'MOVIETWO' => 'MOV1+2',
		 #'MTVClassic' => 'MTVC',
		 'MTV' => 'MTV',
		 'MTVDance' => 'MTVD',
		 #'MTVHits' => 'MTVH',
		 'MTVMusic' => 'MTVM',
		 #'MTVNLive' => 'MTVN',
		 #'MTVNLiveHD' => '',
		 #'' => 'NASIA',
		 'NatGeoAdventure' => 'ADV1',
		 #'NatGeoAdventure2' => '',
		 'NatGeoWild' => 'NGW',
		 #'NatGeoWildHD' => '',
		 'NationalGeographic' => 'NGEO',
		 'NatGeo2' => 'NGEO+2',
		 'NatGeoPeople' => 'NGP',
		 #'NatGeoHD' => '',
		 #'' => 'NBN',
		 #'' => 'NBN-GC',
		 'NHK' => 'HNKW',
		 'Nickelodeon' => 'NICK',
		 'NickJr' => 'NICKJR',
		 'NITV' => 'NITV',
		 #'' => 'ODY',
		 #'' => 'OLY1',
		 #'' => 'OLY2',
		 #'' => 'OLY3',
		 #'' => 'OLY4',
		 #'' => 'OUT-TV',
		 'Ovation' => 'OVAT',
		 #'PlayhouseDisney' => 'PHDISN',
		 'Premiere' => 'FMPREM',
		 'Premiere2' => 'FMPREM+2',
		 #'PremiereHD' => '',
		 #'' => 'PREVIEW',
		 #'RAI' => 'RAI',
		 'Romance' => 'FMDRA',
		 #'RomanceHD' => '',
		 #'RussiaToday' => '',
		 #'' => 'RMTV',
		 #'' => 'RTPI',
		 'SetantaSports' => 'STAS',
		 #'' => 'SENATE',
		 #'' => 'ServiceNSW',
		 'Showcase' => 'SHWC',
		 #'ShowcaseHD' => '',
		 'Showcase2' => 'SHWC+2',
		 #'showtimeaction' => 'SACT',
		 #'showtimeactionHD' => '',
		 #'showtimecomedy' => 'SCOM',
		 #'showtimedrama' => 'SDRA',
		 #'showtimepremiere' => 'SHOW',
		 #'ShowPremiereHD' => '',
		 #'showtimetwo' => 'SHW2',
		 #'' => 'SHWGRTS',
		 'SKYNewsBusiness' => 'SKYB',
		 #'SKYNewsNational' => 'SKYN',
		 #'SKYRacing1' => 'SKYR',
		 #'SKYRacing2' => '',
		 #'SKYRacingWorld' => '',
		 #'SkyThoroughbredCentral' => '',
		 'SKYWeather' => 'SKYW',
		 #'' => 'SPORTSEL',
		 #'' => 'StarMovies',
		 'SoHo' => 'W',
		 'SoHo2' => 'W+2',
		 #'SoHoHD' => '',
		 'SPEED' => 'SPEED',
		 #'SPEEDHD' => '',
		 #'STARPICS1' => 'SPICS',
		 #'STARPICS1HD' => '',
		 #'STARPICS2' => 'SPICS+2',
		 #'STARPICS2HD' => '',
		 #'' => 'StarWorld',
		 #'' => 'STC',
		 #'' => 'STV1',
		 #'STVDIO' => 'STVDIO',
		 'style.' => 'STYLE',
		 'Syfy2' => 'Sci-Fi+2',
		 'Syfy' => 'Sci-Fi',
		 #'SyfyHD' => '',
		 #'' => 'SYRIATV',
		 #'' => 'TABNSW',
		 'TCM' => 'TCM',
		 #'' => 'TDT-Tas',
		 'TheHistoryChannel' => 'HIST',
		 #'TheHistoryChannelHD' => '',
		 #'TheLifeStyleChannel' => 'LIFE',
		 'Thriller' => 'FMCRIM',
		 #'ThrillerHD' => '',
		 #'TheStyleNetwork' => 'STYLE',
		 #'TheWeatherChannel' => 'TWC',
		 'TLC' => 'TLC',
		 'TLC2' => 'TLC+2',
		 #'TSN' => '',
		 #'' => 'TMF',
		 'TVH!ts2' => 'TV1+2',
		 'TVH!ts' => 'TV1',
		 #'' => 'TV5',
		 #'' => 'TVCHILE',
		 #'' => 'TVE',
		 'TVN' => 'TVN',
		 #'' => 'TVS',
		 'TVSNShopping' => 'TVSN',
		 'UKTV2' => 'UKTV+2',
		 'UKTV' => 'UKTV',
		 #'UKTVHD' => '',
		 'Universal' => 'UNIV',
		 'Universal2' => 'UNIV+2',
		 #'UniversalHD' => '',
		 #'Smooth' => '',
		 'VHits' => 'V2',
		 #'' => 'VTV',
		 #'' => 'WEIN',
		 #'' => 'WINE',
		 #'' => 'WLINK',
		 'WorldMovies' => 'WMOV',
		 #'WorldMoviesHD' => '',
		 #'' => 'WTV',
		 #'' => 'WZONE',
	}
);


################################################################################
# Routine for forcing the timezone of a listing to the local time zone.
# This has the effect of mimicing the time-shifting of national programmes
# such as ABC2 for which there is a single programme in, say, Sydney time, but
# where the programmes are broadcast at the same wall clock time everywhere in
# Australia.  
# Care is taken to use the local time zone at the time of the programme.
#
# Also defines a list of OzTivo channels names this kludge should be applied to.
#
sub force_local_timezone($) {
	my $oztivoTime = shift;

	# Split the given time into components ignoring the specified TZ
	# Our input looks like "20080324183000 +1100"
	#
	my ($year, $mon, $mday, $hr, $min, $sec) = $oztivoTime =~ m/^(\d\d\d\d)(\d\d)(\d\d)(\d\d)(\d\d)(\d\d)/;

	# Treat the time as being local and calculate the UNIX time
	# This will account for DST in our time zone.
	#
	my $unixTime = timelocal($sec, $min, $hr, $mday, $mon-1, $year); # expects months 0..11

	# Return a correctly formatted string
	#
	return strftime('%Y%m%d%H%M%S %z', localtime($unixTime));
}

my %force_timezone_set = map { $_ => 1 } ( values %{$s_to_o_map{'National'}} );


################################################################################
# Routines for configuring this grabber
#
sub please_configure_me
{
	print <<__EOM;
If you wish to use $nicename, please run
	tv_grab_au --configure $progname
Configuration of $progname is required
__EOM
}

sub configure
{
	print <<__EOM;
Configuring...

NOTE: This step is currently optional.

You can create an OzTivo account here:
  http://www.oztivo.net/twiki/bin/view/TWiki/TWikiRegistration
... and select some channels here:
  http://www.oztivo.net/tivo-bin/tvguide.pl
When you're done, enter your username and password here, to
enable this grabber to retrieve your guide data automatically:
Username?
__EOM

	my $username = <>;
	chomp $username;
	unless ($username) {
		print "No username supplied. Exiting configuration.\n";
		exit 3;
	}
	print "Password?\n";
	my $pw = <>;
	chomp $pw;
	unless ($pw) {
		print "No password supplied. Exiting configuration.\n";
		exit 3;
	}
	print "Creating config file $config_file...\n";
	open (CONF, ">$config_file")
		or die "Unable to create $config_file: $!";
	print CONF "$username:$pw";
	close CONF;

	print "Done.\n";
	exit 0;
}

sub load_config() {
	unless (-r $config_file) {
		print "Can't find $config_file!\n";
		please_configure_me();
		exit 1;
	}

	print "Reading configuration file $config_file.\n";

	unless (open(CONF, $config_file)) {
		print "Unable to read config file $config_file: $!\n";
		please_configure_me();
		exit 1;
	}
	my $line = <CONF>;
	close CONF;

	unless ($line =~ /^(.*):(.*)$/) {
		print "Unable to parse config file!\n" .
			  "It should be in the format: username:password\n";
		please_configure_me();
		exit 1;
	}
	($user, $pw) = ($1, $2);

	unless ($user and $pw) {
		print "Failed to extract a sensible username and password from config file.\n";
		please_configure_me();
		exit 1;
	}
}

################################################################################
# Local extension of the shared get_url() to cater for password authentication 
# failure
#
# Returns the data as a string, or undef if data could not be retrieved
#
sub get_url($) {
	my ($data, $success, $status, $bytes);

	my $url = shift;

	# Don't rely on Shepherd::Common::get_url()'s retry, because
	# if we get a 401 (wrong password) there's no point in retrying.
	my $max_tries = 3;
	foreach my $tries (1 .. $max_tries) {
		($data, $success, $status, $bytes) = Shepherd::Common::get_url(
				url => $url,
				referer => "Shepherd ".$nicename." grabber, version ".$version,
				delay => "1-3",
				retries => 0);

		last if ($success);

		print "Download failed: $status\n";
		if ($status =~ /401/)
		{
			print <<__EOM;
Your OzTivo username and/or password may be incorrect
The username and password you supplied when configuring the oztivo grabber
must match your registration details on the OzTivo.com site.
If this error persists, try reconfiguring:
	tv_grab_au --configure $progname
__EOM
			last;	# bail out of the retry loop
		}

		my $sleep = 47 + int(rand(120));
		print "Sleeping for $sleep seconds before retrying...\n";
		sleep($sleep);
	}

	# hack: if we don't get back something that looks like xml then try to
	# ungzip it
	if (substr($data,0,1) ne '<') {
		print "Doesn't look like xml, attempting to gunzip.\n";
		$data = Compress::Zlib::memGunzip($data);
	}

	return $data;
} 



################################################################################
#
$| = 1;

GetOptions(
	'config=s'			=> \$config_file,
	'channels_file=s'	=> \$channels_file,
	'output=s'			=> \$output_file,
	'version'			=> \$ver,
	'ready'				=> \$ready_check,
	'configure'			=> \$configure,
	'region=s'			=> \$region,
	'days:i'			=> \$days,			# Optional
);

print "$nicename Grabber v$version\n";
exit 0 if ($ver);	# Just print the version and leave

# Do the configuration if requested
# Load the configuration otherwise
#
configure() if ($configure);
#load_config();

exit 0 if ($ready_check);	# Just print the version and leave

# Idiot checks on mandatory options
#
unless (defined($output_file)) {
	die "No --output file specified.\n";
}
unless (defined($region)) {
	die "No --region specified.\n";
}

# Import the Shepherd channels configuration
#
unless ($channels_file) { 
	die "No --channels_file specified.\n";
}
unless( -r $channels_file) { 
	die "Unable to read channels file $channels_file: $!";
}
{	# Block localises the variables
	local (@ARGV, $/) = ($channels_file);
	eval <>;
	die "\nError in channels file!\nDetails:\n$@" if ($@);
}


# Create the in-memory form of the output file
#
my $outdom = XML::LibXML::Document->new( '1.0', 'iso-8859-1' );
my $root = $outdom->createElement('tv');
$root->setAttribute('generator-info-name', $progname);
$outdom->setDocumentElement($root);

# Calculate the start and end date for the days requested
# #
my ($mday, $mon, $year) = (localtime)[3..5];
my $startdate = sprintf('%04d-%02d-%02d', $year+1900, $mon+1, $mday);
($mday, $mon, $year) = (localtime(time + ($days-1)*86400) )[3..5];
my $enddate = sprintf('%04d-%02d-%02d', $year+1900, $mon+1, $mday);

# Get the OzTivo datalist.xml file and interrogate it for;
# The base URL for each channel
# The data files available for today onward including their 
#	last modified date.
#

my $datalist = get_url("http://xml.oztivo.net/xmltv/datalist.xml.gz");
unless (defined($datalist)) {
	die "\nError fetching data list xml file!\n";
}

# Make the user credentials safe
#my $credentials = uri_escape($user) .':' . uri_escape($pw);

my $dlparser = XML::LibXML->new();		# For the datalist.xml file
my $progparser = XML::LibXML->new();	# For the programme data files

my $dlxml = $dlparser->parse_string($datalist);
foreach my $sname ( keys(%$channels), keys(%$opt_channels) ) {
	# Work out which OzTivo channel this Shepherd channel is
	# 
	# The order of search for a mapping is;
	# 	Region specific mapping (under numeric region code keys)
	#	National mapping (under hash key 'National')
	#	Pay TV mapping (under hash key 'PAY')
	# First mapping found wins.
	#
	my $oname = $s_to_o_map{$region}->{$sname};
	if (! defined($oname)) {
		$oname = $s_to_o_map{&Shepherd::Common::which_state($region)}->{$sname};
	}
	if (! defined($oname)) {	# Try a National channel
		$oname = $s_to_o_map{'National'}->{$sname};
	}
	if (! defined($oname)) {	# Try a PAY channel
		$oname = $s_to_o_map{'PAY'}->{$sname};
	}
	unless (defined($oname)) {
		print "\nNo region $region mapping from " .
			"Shepherd channel $sname to OzTivo channel\n\n";
		next;
	}

	# What XMLTV id is this channel. May be in either channels hash
	#
	my $xmltvid = defined($channels->{$sname}) ?  
		$channels->{$sname}: $opt_channels->{$sname};
	unless (defined($xmltvid)) {
		print "\nNo XMLTV id for Shepherd channel $sname\n\n";
		next;
	}

	# Construct a clone of select parts of the channel element in the output document.
	# Ignores non-XMLTV elements present in the datalist.xml file.
	#
	my ($channelnode) = $dlxml->findnodes('/tv/channel[@id="' . $oname . '"]');
	unless (defined($channelnode)) {
		print "\nCannot find the $oname channel element in the datalist.xml file\n";
		next;
	}
	my $newnode = $channelnode->cloneNode(0);
	$newnode->setAttribute('id', $xmltvid);
	foreach my $node ($channelnode->findnodes('display-name|url|icon')) {
		$newnode->appendChild($node->cloneNode(1));
	}
	$root->insertBefore($newnode, $root->firstChild);

	
	# Get the first base URL for the channel
	# and mangle our user name and password into it
	#
	my $baseurl = $dlxml->findvalue('/tv/channel[@id="' . $oname . '"]/base-url[1]');
	unless (defined($baseurl)) {
		print "\nCannot find the $oname baseurl in the datalist.xml file\n";
		next;
	}
	#$baseurl =~ s!^(https?://)!$1$credentials\@!;

	# Process the list of data files for today or later
	#
	my @datafornodes = $dlxml->findnodes('/tv/channel[@id="' . $oname . '"]/datafor');
	unless (@datafornodes) {
		print "\nCannot find the $oname datafor records in the datalist.xml file\n";
		next;
	}
	foreach my $datafornode (@datafornodes) {
		my $filedate = $datafornode->findvalue('child::text()');

		if ($filedate ge $startdate && $filedate le $enddate ) {	# Today or future data
			# Build the source file name and fetch it
			# 
			my $url = $baseurl . uri_escape( $oname . '_' . $filedate . '.xml.gz' );
			my $progdata = get_url($url);
			unless ($progdata) {
				print "\nCannot retrieve the $oname programme data for $filedate\n";
				next;
			}

			# We have the data we need to actually build the output file
			#
			my $progxml = $progparser->parse_string($progdata);
			my @prognodes = $progxml->findnodes('/tv/programme');
			unless (@prognodes) {
				print "\nCannot find the $oname programme records in the $filedate file\n";
				next;
			}
			foreach my $prognode (@prognodes) {
				# Remove the node from the source document and make it part of
				# our output document.
				#
				$outdom->adoptNode($prognode);
				$root->appendChild($prognode);

				# If there are <star-rating> element(s) present and they contain 
				# a <value> element with '0/10' then delete the <star-rating>.
				# OzTivo data uses this to mean 'Unrated' rather than 'Terrible programme'.
				# This rating is used by the post-processors and skews their results.
				#
				my @ratings = $prognode->findnodes("star-rating[value='0/10']");
				foreach my $rating (@ratings) {
					$rating->unbindNode();
				}
				

				# Correct the channel attribute to use our desired XMLTV id
				# as specified in the channels.conf file.
				#
				$prognode->setAttribute('channel', $xmltvid);

				# If necessary force the local time zone onto the start and end times
				#
				if ($force_timezone_set{$oname}) {
					my $starttime = force_local_timezone($prognode->getAttribute('start'));
					my $stoptime = force_local_timezone($prognode->getAttribute('stop'));
					$prognode->setAttribute('start', $starttime);
					$prognode->setAttribute('stop', $stoptime);
				}
			}
			$progxml = undef;
		}
	}
}
$dlxml = undef;

# Write the output
#
$outdom->toFile($output_file, 1)
	or die "\nCould not create output file $output_file\n";

